### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by theolampert** [nekonora/TaggerKit#16]
Would be great to have SPM supported, is this something you'd want a PR for?

**Comment by nekonora** [comment]
Hey, I actually already tried it, but this project relies heavily on UIKit, and I have yet to find a way (if at all possible at the moment) to make a SPM library that supports it. It doesn't seem possible at the moment but I might be overlooking something.

**Comment by theolampert** [comment]
I think Xcode 11 will be able to build the package with a dependency on `UIKit` but the `swift build` command will not work (which is fine since this is an iOS library). But I might be wrong here.

If you like I can take a look into this later on.

**Comment by nekonora** [comment]
Sure, thanks!

**Comment by nekonora** [comment]
Closing this as it seems to work when adding the repo in Xcode 11. @theolampert
