### ISSUE TITLE
Unknown Process Name warning messages

### ISSUE THREAD

**Issue by daviddelmonte** [nekonora/TaggerKit#20]
This is a great control. Thank you. However, I'm getting a slew of warning messages:

`TaggerKit_Example[12045:882350] [Unknown process name] CGContextDrawPath: invalid context 0x0. If you want to see the backtrace, please set CG_CONTEXT_SHOW_BACKTRACE environmental variable.`

This is 10.14.6, but using Xcode11.0.

**Comment by nekonora** [comment]
Thanks, these (I think) appeared after having switched to code-drawn icon shapes for tags (the plus and the delete default signs). Prior to that I was using classic assets but it was not ideal for a library and also not compatible with SPM.

Although I also find them annoying, they don't seem (at least for now) to be causing any trouble and I haven't found the time ti give it a look yet. :) I'll make sure to get rid of them anyway.

**Comment by daviddelmonte** [comment]
Thanks Filippo, no rush at all..

**Comment by daviddelmonte** [comment]
Brilliant. Thank you
