### ISSUE TITLE
Simpler, more manageable collection object

### ISSUE THREAD

**Issue by nekonora** [nekonora/TaggerKit#22]
A new simpler container for tags, a simple (IB-friendly) UIView subclass that doesn't need to be added as a child controller. Although the old method will still be available for the time being, it will be deprecated by this.

**Comment by rittermobile** [comment]
Do you have any timeline when the feature branch / new release will be finished?

**Comment by nekonora** [comment]
Hey @rittermobile unfortunately I don't really have any timeline for now but, given the current situation, there's a chance I'll be able to work on this a little more.
