### ISSUE TITLE
update alltag view

### ISSUE THREAD

**Issue by fukemy** [nekonora/TaggerKit#28]
hello, after used project, i think better is change allTags view with dropdown for more flexible and comfortable, can u give me some advice to do it? Thanks

**Comment by nekonora** [comment]
Hi! If I correctly understood your wish, you could do that in a various number of ways, I suppose. For example inserting a tag view as a view into a UIStackView. That makes it easy to animate appearance/disappearance by just setting the tag view as hidden or not.

**Comment by fukemy** [comment]
thanks, i found it were easier when using [Dropdown](https://github.com/AssistoLab/DropDown)
