### ISSUE TITLE
Can't install using Cocoapods

### ISSUE THREAD

**Issue by hakimny** [nekonora/TaggerKit#3]
pod 'TaggerKit', '~> 0.4'

error
[!] Unable to find a specification for `TaggerKit`

**Comment by nekonora** [comment]
Have you checked your podfile and/or your installation?

**Comment by hakimny** [comment]
All good in my end, I am able to install other pods with no problems.

**Comment by hakimny** [comment]
not sure how to explain it but the following made my day:
pod repo update
pod install
