### ISSUE TITLE
How to use TaggerKit with Dynamic height?

### ISSUE THREAD

**Issue by StellarKuldeep** [nekonora/TaggerKit#5]
I want to change the ContainerView height as per the Tags. how can I do this?

**Comment by nekonora** [comment]
Hi, I'm assuming you'd like to dynamically change the container's height depending of the number of tags (or better rows of them)? 

If that's your goal, you should probably set the container's constraints programatically with a function that calculates how many rows you have based on tags' length and container width (approximate example: total tags lenght / container width = number of rows). 

For any other question please let me know on twitter.

**Comment by KetaniOS-Pankhuri** [comment]
@nekonora 
it will be really helpful if you write down proper code?
